import { publicPageMetadata } from "@/lib/seo";
import Link from "next/link";
import { getSiteUrl } from "@/lib/site";
export const metadata = publicPageMetadata("/integrations", "Connect your assistant | LearningMap", "Connect an MCP-compatible assistant after signing in and creating a scoped LearningMap agent key.");
export default function IntegrationsPage() {
  const endpoint = getSiteUrl() + "/mcp";
  return <div className="mx-auto max-w-4xl px-5 py-16 sm:px-8">
    <p className="text-sm uppercase tracking-widest text-slate-400">LearningMap for assistants</p>
    <h1 className="mt-4 font-serif text-4xl font-semibold text-white">A clearer path, wherever you learn.</h1>
    <p className="mt-5 max-w-2xl text-lg leading-relaxed text-slate-300">Use LearningMap inside an MCP-compatible bot to explore learning fields, curriculum outlines and curated resources. MCP is the connection that lets your assistant read this catalog.</p>
    <section className="mt-10 rounded-2xl border border-slate-700 bg-slate-900 p-6 sm:p-8" aria-labelledby="connect-heading">
      <h2 id="connect-heading" className="text-2xl font-semibold">Connect your assistant</h2>
      <ol className="mt-5 list-decimal space-y-3 pl-5 text-slate-300"><li><Link className="underline underline-offset-4" href="/login?next=%2Fsettings%2Fagents">Sign in to your LearningMap account</Link> with a verified email address. If you have not verified it, complete email verification first.</li><li>Open <Link className="underline underline-offset-4" href="/settings/agents">Settings → Agent access</Link>, name your bot, confirm your account password and approve read-only catalog access. Copy the key when it appears; it is shown only once.</li><li>Add a remote server using Streamable HTTP and the address below.</li><li>Add the header <code>Authorization: Bearer YOUR_AGENT_KEY</code> in your assistant’s connection settings, replacing <code>YOUR_AGENT_KEY</code> with your key. Store it in the client’s private credential settings.</li><li>Ask your assistant: “Show me a beginner backend development curriculum from LearningMap.”</li></ol>
      <p className="mt-6 text-sm text-slate-400">Server address</p><code className="mt-2 block break-all rounded-lg border border-slate-700 p-4 text-slate-100">{endpoint}</code>
      <p className="mt-4 text-sm text-slate-400">Your client must support remote MCP with a custom Authorization header. Never give a bot your email password or browser cookies. If your account uses Google sign-in, set a password through the password-reset page before creating a key. Automatic OAuth sign-in is not offered in this version. This does not automatically register LearningMap with Grok, Dots or another bot.</p>
    </section>
    <section className="mt-10" aria-labelledby="tools-heading"><h2 id="tools-heading" className="text-2xl font-semibold">What your assistant can explore</h2><ul className="mt-5 list-disc space-y-3 pl-5 text-slate-300"><li>Six learning fields and three experience levels.</li><li>Authored curriculum previews with projects and estimated study hours.</li><li>Curated learning resources searchable by title and topic.</li></ul><p className="mt-5 text-slate-400">Previews are not saved or personalized roadmaps. Resource availability and free access are not checked live; confirm current terms on the provider website.</p></section>
    <section className="mt-10" aria-labelledby="privacy-heading"><h2 id="privacy-heading" className="text-2xl font-semibold">Your learning stays yours</h2><p className="mt-4 text-slate-300">This integration cannot read your account, notes or saved progress, purchase courses, send emails, or change your calendar. The key only grants catalog read access. Revoke it in Settings → Agent access whenever you want. Keys expire after 30 days. Website sign-out does not revoke keys; revoke a key immediately if it is lost or exposed.</p></section>
    <nav aria-label="Integration resources" className="mt-10 flex flex-wrap gap-6 text-slate-200"><Link className="underline underline-offset-4" href="/settings/agents">Manage agent access</Link><a className="underline underline-offset-4" href="/llms.txt">Agent guide</a><Link className="underline underline-offset-4" href="/onboarding">Build your own roadmap</Link></nav>
  </div>;
}
