-- ============================================================
-- Migration 003: pending_path_sets
--
-- Replaces lib/db/in-memory-paths.ts. That module stored the "3
-- generated options, pick one" state in a process-global JS Map, which
-- does not survive across Vercel serverless instances — a path
-- generated by one instance is frequently invisible to the instance
-- that serves the confirmation step, causing "Path session expired"
-- errors or, worse, the app silently falling back to fabricated
-- placeholder content. This table makes that state durable and
-- properly owner-scoped via RLS instead of an in-memory value with no
-- ownership check at all.
-- ============================================================

create table public.pending_path_sets (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  field_id uuid not null references public.fields(id) on delete restrict,
  skill_level text not null check (skill_level in ('beginner', 'intermediate', 'advanced')),
  weekly_hours integer not null,
  budget_total numeric(10,2) not null default 0,
  currency text not null default 'USD',
  -- Each option's stages/resources/practice_check, exactly as built by
  -- generateMultiplePathOptions(). This is intentionally transient,
  -- pre-selection data, so it's stored as JSON rather than normalized
  -- into stages/stage_resources — only the option the user actually
  -- picks gets normalized into those tables, at confirmation time.
  options jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '1 hour')
);

create index idx_pending_path_sets_user_id on public.pending_path_sets(user_id);

alter table public.pending_path_sets enable row level security;

create policy "pending_path_sets_owner_all"
  on public.pending_path_sets for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Optional cleanup: rows older than their expiry are harmless to leave
-- (owner-scoped, small), but you may want a periodic job later to
-- delete where expires_at < now(). Not required for correctness.
