begin;
-- Options are generated by the server. Never allow forged JSON through direct REST writes.
revoke insert, update, delete on public.pending_path_sets from anon, authenticated;
drop policy if exists pending_path_sets_owner_all on public.pending_path_sets;
create policy pending_path_sets_owner_read on public.pending_path_sets for select to authenticated
 using (user_id = (select auth.uid()) and expires_at > now());
-- Both the progress row and its parent stage must belong to the caller.
drop policy if exists stage_progress_owner_all on public.stage_progress;
create policy stage_progress_owner_all on public.stage_progress for all to authenticated
 using (user_id = (select auth.uid()) and exists (
 select 1 from public.stages s join public.learning_paths p on p.id=s.path_id
 where s.id=stage_progress.stage_id and p.user_id=(select auth.uid())))
 with check (user_id = (select auth.uid()) and exists (
 select 1 from public.stages s join public.learning_paths p on p.id=s.path_id
 where s.id=stage_progress.stage_id and p.user_id=(select auth.uid())));
-- Ratings need not expose users' identifiers to all signed-in accounts.
drop policy if exists resource_ratings_select_all on public.resource_ratings;
create policy resource_ratings_select_own on public.resource_ratings for select to authenticated using(user_id=(select auth.uid()));
alter function public.is_admin() set search_path = '';
alter function public.prevent_role_escalation() set search_path = '';
commit;
